server:
  port: 8090
logging:
  level:
    root: info
qwen:
  secret_key: sk-46f2d279e28345408ca38870f69d6cc8
redis:
  server: localhost
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true